trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:

# ======================
# BUILD
# ======================
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    steps:

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet restore
      displayName: Restore

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: Build

    - script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
      displayName: Publish

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        
- stage: Deploy_DEV
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureWebApp@2
            inputs:
              azureSubscription: 'AZURE-SERVICE-CONNECTION'
              appName: 'minieshop-storefront-dev'
              package: '$(Pipeline.Workspace)/drop'